/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_Record;
import javax.swing.table.DefaultTableModel;
import modelo.Puntos;
import modelo.Registro_Puntos;

/**
 *
 * @author frnnd
 */
public class FRM_Record extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Record
     */
    
    Controlador_FRM_Record controlador_FRM_Record;
    DefaultTableModel modelo;
    Registro_Puntos registro;
    
    public FRM_Record(Registro_Puntos registro_Puntos) {
        initComponents();
        this.registro=registro_Puntos;
        setLocationRelativeTo(null);
        modelo=new DefaultTableModel();
        jtbl_Puntos.setModel(modelo);
        String titulos[]=new String[2];
        titulos[0]="Ganador";
        titulos[1]="Puntos";
        modelo.setColumnIdentifiers(titulos);

        controlador_FRM_Record= new Controlador_FRM_Record(this);
        jbtn_Back.addActionListener(controlador_FRM_Record);
        
    }//Fin constructor
    
    public void cargarFilas(){
        for(int contador=0;contador<registro.getSize();contador++){
            modelo.addRow(registro.devolverFila(contador));
        }//Fin for
    }//Fin cargarFilas
    
    public void limpiarFilas(){
        for(int contador=0;contador<modelo.getRowCount();contador++){
            modelo.removeRow(0);
            System.out.println("borró "+contador);
        }//Fin for
    }//Fin metodo
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_Puntos = new javax.swing.JTable();
        jbtn_Back = new javax.swing.JButton();
        jl_FondoBola = new javax.swing.JLabel();
        jl_Fondo = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtbl_Puntos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbl_Puntos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 370, 450));

        jbtn_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/elementos_Informacion/botonBack.png"))); // NOI18N
        jbtn_Back.setActionCommand("Back");
        jbtn_Back.setBorderPainted(false);
        jbtn_Back.setContentAreaFilled(false);
        getContentPane().add(jbtn_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, -1, -1));

        jl_FondoBola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/elementos_MenuInicio/fondoBola.png"))); // NOI18N
        getContentPane().add(jl_FondoBola, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/elementos_MenuInicio/fondoMenuInicio1.jpg"))); // NOI18N
        getContentPane().add(jl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_Back;
    private javax.swing.JLabel jl_Fondo;
    private javax.swing.JLabel jl_FondoBola;
    private javax.swing.JTable jtbl_Puntos;
    // End of variables declaration//GEN-END:variables
}
