/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_MenuInicio;

/**
 *
 * @author Admin
 */
public class FRM_MenuInicio extends javax.swing.JFrame {

    /**
     * Creates new form FRM_MenuInicio
     */
    
    Controlador_FRM_MenuInicio controlador_FRM_MenuInicio;
    
    public FRM_MenuInicio() {
        initComponents();
        setLocationRelativeTo(null);
        controlador_FRM_MenuInicio=new Controlador_FRM_MenuInicio(this);
        jbtn_Play.addActionListener(controlador_FRM_MenuInicio);
        jbtn_Informacion.addActionListener(controlador_FRM_MenuInicio);
        jbtn_Instrucciones.addActionListener(controlador_FRM_MenuInicio);
        jbtn_Record.addActionListener(controlador_FRM_MenuInicio);
        
    }//Fin controlador

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn_Informacion = new javax.swing.JButton();
        jbtn_Play = new javax.swing.JButton();
        jbtn_Instrucciones = new javax.swing.JButton();
        jbtn_Record = new javax.swing.JButton();
        jl_FondoMenuInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1017, 840));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn_Informacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/elementos_MenuInicio/botonInformacion.png"))); // NOI18N
        jbtn_Informacion.setActionCommand("Informacion");
        jbtn_Informacion.setBorderPainted(false);
        jbtn_Informacion.setContentAreaFilled(false);
        getContentPane().add(jbtn_Informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, 80, 80));

        jbtn_Play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/elementos_MenuInicio/botonPlayVerdadero.png"))); // NOI18N
        jbtn_Play.setActionCommand("Play");
        jbtn_Play.setBorderPainted(false);
        jbtn_Play.setContentAreaFilled(false);
        jbtn_Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_PlayActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_Play, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 530, -1, -1));

        jbtn_Instrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/elementos_MenuInicio/botonInstrucciones.png"))); // NOI18N
        jbtn_Instrucciones.setActionCommand("Instrucciones");
        jbtn_Instrucciones.setBorderPainted(false);
        jbtn_Instrucciones.setContentAreaFilled(false);
        getContentPane().add(jbtn_Instrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 530, 80, 80));

        jbtn_Record.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/elementos_MenuInicio/botonPlay.png"))); // NOI18N
        jbtn_Record.setActionCommand("Record");
        jbtn_Record.setBorderPainted(false);
        jbtn_Record.setContentAreaFilled(false);
        getContentPane().add(jbtn_Record, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, -1, -1));

        jl_FondoMenuInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/elementos_MenuInicio/fondoMenuInicio2.jpg"))); // NOI18N
        getContentPane().add(jl_FondoMenuInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_PlayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_PlayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_MenuInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn_Informacion;
    private javax.swing.JButton jbtn_Instrucciones;
    private javax.swing.JButton jbtn_Play;
    private javax.swing.JButton jbtn_Record;
    private javax.swing.JLabel jl_FondoMenuInicio;
    // End of variables declaration//GEN-END:variables
}
