/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_Informacion;

/**
 *
 * @author frnnd
 */
public class FRM_Informacion extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Informacion
     */
    Controlador_FRM_Informacion controlador_FRM_Informacion;

    public FRM_Informacion() {
        initComponents();
        setLocationRelativeTo(null);

        controlador_FRM_Informacion = new Controlador_FRM_Informacion(this);

        jbtn_Back.addActionListener(controlador_FRM_Informacion);
        
    }//Fin controlador

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Historia = new javax.swing.JLabel();
        jbtn_Back = new javax.swing.JButton();
        jl_Fondo = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_Historia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/elementos_Informacion/ventanaInformaciónFinal.png"))); // NOI18N
        getContentPane().add(jl_Historia, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        jbtn_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/elementos_Informacion/botonBack.png"))); // NOI18N
        jbtn_Back.setActionCommand("Back");
        jbtn_Back.setBorderPainted(false);
        jbtn_Back.setContentAreaFilled(false);
        getContentPane().add(jbtn_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, -1, -1));

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/elementos_MenuInicio/fondoMenuInicio1.jpg"))); // NOI18N
        getContentPane().add(jl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn_Back;
    private javax.swing.JLabel jl_Fondo;
    private javax.swing.JLabel jl_Historia;
    // End of variables declaration//GEN-END:variables
}
