/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_Instrucciones;

/**
 *
 * @author frnnd
 */
public class FRM_Intrucciones extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Intrucciones
     */
    
    Controlador_FRM_Instrucciones controlador_FRM_Instrucciones;
    
    public FRM_Intrucciones() {
        initComponents();
        setLocationRelativeTo(null);
        
        controlador_FRM_Instrucciones=new Controlador_FRM_Instrucciones(this);
        
        jbtn_Back.addActionListener(controlador_FRM_Instrucciones);
        
    }//Fin controlador

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Instrucciones = new javax.swing.JLabel();
        jbtn_Back = new javax.swing.JButton();
        jl_Fondo = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_Instrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/elementos_Informacion/ventanaInstrucciones.png"))); // NOI18N
        getContentPane().add(jl_Instrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        jbtn_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/elementos_Informacion/botonBack.png"))); // NOI18N
        jbtn_Back.setActionCommand("Back");
        jbtn_Back.setBorderPainted(false);
        jbtn_Back.setContentAreaFilled(false);
        getContentPane().add(jbtn_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, -1, -1));

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/elementos_MenuInicio/fondoMenuInicio1.jpg"))); // NOI18N
        getContentPane().add(jl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn_Back;
    private javax.swing.JLabel jl_Fondo;
    private javax.swing.JLabel jl_Instrucciones;
    // End of variables declaration//GEN-END:variables
}
